spring:
#  spring.redis.host=localhost
#  spring.redis.port=6379
  redis:
    host: localhost
    port: 6379
  config:
    import: optional:configserver:http://localhost:50000  # test
  profiles:
    active: user