server:
  port: 5001

#spring.cloud.gateway.server.webflux.discovery.locator.enabled: true
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:50000
  profiles:
    active: apigateway
  cloud:
    gateway:
      server:
        webflux:   
          # This is for static routing
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
            - id: lab-service
              uri: lb://lab-service
              predicates:
                - Path=/lab/**
            - id: appointment-service
              uri: lb://appointment-service
              predicates:
                - Path=/appointment/**
            - id: prescription-service
              uri: lb://prescription-service
              predicates:
                - Path=/prescription/**
            - id: pharmacy-service
              uri: lb://pharmacy-service
              predicates:
                - Path=/pharmacy/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/payment/**
            - id: report-service
              uri: lb://report-service
              predicates:
                - Path=/report/**
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/notification/**

      # This is for rate limiting 
      default-filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@ipKeyResolver}"
            redis-rate-limiter.replenish-rate: 10 # number of requests per second
            redis-rate-limiter.burst-capacity: 20 # maximum number of requests in a burst

    # Uncomment below lines and comment the above static routing if you want to use dynamic routing using eureka server
    # gateway:
      # This is for dynamic routing using eureka server
      # server:
      #   webflux:
      #     discovery:
      #       locator:
      #         enabled: true
      #         lower-case-service-id: true

      # Below is the static routing configuration if you want to use dynamic routing then use eureka server
      # If you want to use eureka server then uncomment below line and comment the static routing
      # routes:
      #   - id: user-service
      #     uri: http://localhost:5002
      #     predicates:
      #       - Path=/user/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  

info:
  app:
    name: ${spring.application.name}
    description: "API Gateway for Lab Equipped"
    version: "1.0.0"
